### ISSUE TITLE
ImportError: cannot import name 'duck_array_type' from 'xarray.core.pycompat'

### ISSUE THREAD

**Issue by onlyred87** [yt87/pywgrib2_xr#4]
### Describe the bug  
I tried to import pywgrib2_xr and got this error:  

         Traceback (most recent call last):  
         File "<stdin>", line 1, in <module>  
         File "/opt/anaconda3/envs/env_pywgrib2/lib/python3.8/site-packages/pywgrib2_xr/__init__.py", line 30, in <module> from .accessor import Wgrib2DatasetAccessor  
         File "/opt/anaconda3/envs/env_pywgrib2/lib/python3.8/site-packages/pywgrib2_xr/accessor.py", line 10, in <module> from xarray.core.pycompat import duck_array_type  
         ImportError: cannot import name 'duck_array_type' from 'xarray.core.pycompat' (/opt/anaconda3/envs/env_pywgrib2/lib/python3.8/site-packages/xarray/core/pycompat.py)  

### Environment Info:

OS: Ubuntu 20.04

**Comment by onlyred87** [comment]
It was solved by installing the 0.20.1 version of xarray.

**Comment by douglatornell** [comment]
I encountered this recently too. I dug into it a little, posted to the [xarray Q&A discussion](https://github.com/pydata/xarray/discussions/7569), and got some insight from there.
